### PR TITLE
feat: add blog root path config

### PR DESCRIPTION
**Pull request by XilongYang**
Some users deploys their blog under other site (such as me :>), it cause the '/' is not the home page of their blog. It's necessary to add a config to allow users specify their own root path.

### CODE REVIEW

**Comment by XPoet** [comment]
非常好的配置项，请往 dev 分支提 PR

**Comment by XilongYang** [comment]
> 

已更改到dev分支

**Comment by XilongYang** [comment]
@XPoet 你好，这个PR的冲突已解决

**Comment by XPoet** [comment]
The blog root path question has been handled perfectly in `v4.0.2`.

Thank you for your PR.

**Pull request closed without merging**
